config/routes.rb
Rails.application.routes.draw do

  devise_scope :customer do
  post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
 end

  scope module: :public do
    root to: "homes#top"

    resource :customers, only:[:edit, :update] do
      get "mypage" => "customers#show"
    end

    resources :reservations, only:[:index, :new, :create, :destroy] do
      member do
        get "complete" => "reservations#complete"
      end
    end

    resources :menus, only:[:index]

    resources :notices, only:[:index] do
      member do
        get "show" => "notices#show"
      end
      collection do
        get "search_tag" => "notices#search_tag"
      end
      resources :reviews, only: [:index, :create]
    end
  end

  namespace :admin do
    root to: "homes#top"

    resources :menus, only:[:index, :new, :create, :destroy]

    resources :notices, only:[:index, :show, :new, :create, :update, :destroy] do
      collection do
        get "search_tag" => "notices#search_tag"
      end
    end

    resources :customers, only:[:index]

    resources :reservations, only:[:index]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip:[:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
class Menu < ApplicationRecord

  validates :menu_title, presence: true
  validates :menu_sub_title, presence: true
  validates :menu_explanation, presence: true
  validates :price, presence: true
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController

  def index
    @menus = Menu.page(params[:page]).per(6)
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to admin_menus_path
    else
      @menus = Menu.page(params[:page]).per(6)
      render 'index'
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    redirect_to admin_menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:menu_title, :menu_sub_title, :menu_explanation, :price)
  end
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/views/admin/menus/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>メニュー一覧</h1>
      <p>当店で取り扱っているメニューになります</p>
    </div>
  </div>
  <div class="row">
    <% @menus.each do |menu| %>
    <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
        <div class="card-body shadow-lg">
          <h5 class="card-title"><%= menu.menu_title %></h5>
          <h6 class="card-subtitle mb-2 text-body-secondary"><%= menu.menu_sub_title %></h6>
          <p class="card-text"><%= menu.menu_explanation %></p>
          <p class="card-text"><%= menu.price %>円</p>
          <div>
            <%= link_to '削除', admin_menu_path(menu.id), method: :delete, data: { confirm: "削除してよろしいですか？", commit: "削除する", cancel: "やめる", title: "ご確認ください" } %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<%= paginate @menus %>

<div class="text-center">
    <%= link_to "メニュー新規追加", new_admin_menu_path, class:"btn btn-success" %>
</div>

app/views/admin/menus/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>メニュー新規登録</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @menu, url:admin_menus_path do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :menu_title, "タイトル" %></th>
            <th><%= f.text_field :menu_title, placeholder:"タイトル名" %></th>
          </div>
        </tr>

        <tr>
          <div class="form-group">
            <th><%= f.label :menu_sub_title, "サブタイトル" %></th>
            <th><%= f.text_field :menu_sub_title, placeholder:"subtitle" %></th>
          </div>
        </tr>

        <tr>
          <div class="form-group">
            <th><%= f.label :menu_explanation, "説明" %></th>
            <th><%= f.text_field :menu_explanation, placeholder:"説明文", size: "50x4" %></th>
          </div>
        </tr>

         <tr>
          <div class="form-group">
            <th><%= f.label :price, "価格" %></th>
            <th><%= f.text_field :price, placeholder:"1000" %>円</th>
          </div>
        </tr>
      </table>
      　<div class="col-sm-2 mx-auto text-center">
          <div><%= f.submit "新規登録", class:"btn btn-success" %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>