config/routes.rb
Rails.application.routes.draw do

  devise_scope :customer do
  post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
 end

  scope module: :public do
    root to: "homes#top"

    resource :customers, only:[:edit, :update] do
      get "mypage" => "customers#show"
    end

    resources :reservations, only:[:index, :new, :create, :destroy] do
      member do
        get "complete" => "reservations#complete"
      end
    end

    resources :menus, only:[:index]

    resources :notices, only:[:index] do
      member do
        get "show" => "notices#show"
      end
      collection do
        get "search_tag" => "notices#search_tag"
      end
      resources :reviews, only: [:index, :create]
    end
  end

  namespace :admin do
    root to: "homes#top"

    resources :menus, only:[:index, :new, :create, :destroy]

    resources :notices, only:[:index, :show, :new, :create, :update, :destroy] do
      collection do
        get "search_tag" => "notices#search_tag"
      end
    end

    resources :customers, only:[:index]

    resources :reservations, only:[:index]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip:[:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_many :notice_tags,dependent: :destroy
  has_many :tags,through: :notice_tags
  has_many :reviews,dependent: :destroy

  validates :title, presence: true
  validates :deadline, presence: true
  validates :explanation, presence: true

  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController

  def index
    @notices = Notice.page(params[:page]).per(10).order(created_at: :desc)
    @tag_list = Tag.all
  end

  def show
    @notice = Notice.find(params[:id])
    @notice_tags = @notice.tags
    @reviews = @notice.reviews
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = Notice.new(notice_params)
    tag_list=params[:notice][:name].split(',')
    if @notice.save
      @notice.save_tag(tag_list)
      redirect_to admin_notices_path
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_notices_path
  end

  def search_tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @notices = @tag.notices
  end

  private

    def notice_params
      params.require(:notice).permit(:title, :deadline, :explanation)
    end
end

app/helpers/admin/notices_helper.rb
module Admin::NoticesHelper
end

app/views/admin/notices/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>お知らせ一覧</h2>
      <div>
        <% @tag_list.each do |list| %>
          <i class="fa-sharp fa-solid fa-tag"></i>
          <%= link_to list.name, search_tag_admin_notices_path(tag_id: list.id) %>
          <%="(#{list.notices.count})" %>
        <% end %>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>タイトル</th>
            <th></th>
            <th>期限</th>
          </tr>
        </thead>
        <tbody>
          <% @notices.each do |notice| %>
            <tr>
              <td><%= link_to notice.title, admin_notice_path(notice.id) %></td>
              <td><%= notice.avg_score %>点（<%= notice.reviews.count %>件のレビュー）</td>
              <td><%= notice.deadline %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @notices %>
    </div>
  </div>
</div>

<div class="text-center">
  <%= link_to "お知らせ新規追加", new_admin_notice_path, class:"btn btn-success" %>
</div>

app/views/admin/notices/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>お知らせ新規登録</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @notice, url:admin_notices_path do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :title, "タイトル" %></th>
            <th><%= f.text_field :title, placeholder:"タイトル名" %></th>
          </div>
        </tr>

        <tr>
          <div class="form-group">
            <th><%= f.label :deadline, "期限" %></th>
            <th><%= f.text_field :deadline, placeholder:"11/01から12/31まで" %></th>
          </div>
        </tr>

        <tr>
          <div class="form-group">
            <th><%= f.label :explanation, "説明" %></th>
            <th><%= f.text_field :explanation, placeholder:"説明文", size: "50x4" %></th>
          </div>
        </tr>

        <tr>
          <div class="form-group">
            <th><%= f.label"タグ (,で区切ると複数タグ登録できます)" %></th>
            <th><%= f.text_field :name,value: @tag_list %></th>
          </div>
        </tr>
      </table>
      　<div class="col-sm-2 mx-auto text-center">
          <div><%= f.submit "新規登録", class:"btn btn-success" %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/notices/search_tag.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>タグが<strong><%=@tag.name%></strong>の投稿一覧</h2>
      <% @tag_list.each do |list|%>
        <i class="fa-sharp fa-solid fa-tag"></i>
        <%=link_to list.name, search_tag_admin_notices_path(tag_id: list.id) %>
        <%="(#{list.notices.count})" %>
      <% end %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th></th>
          <th>期限</th>
        </tr>
      </thead>
      <tbody>
        <% @notices.each do |notice| %>
          <tr>
            <td><%= link_to notice.title, admin_notice_path(notice.id) %></td>
            <td><%= notice.avg_score %>点（<%= notice.reviews.count %>件のレビュー）</td>
            <td><%= notice.deadline %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/notices/show.html.erb
<div class="container">
  <div class="row">
    <div>
      <% @notice_tags.each do |tag| %>
        <%=tag.name%><%="(#{tag.notices.count})" %>
      <% end %>
    </div>
    <div class="col">
      <h2>お知らせ詳細</h2>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <tbody>
        <tr>
          <td>タイトル</td>
          <td><%= @notice.title %></td>
        </tr>

        <tr>
          <td>期限</td>
          <td><%= @notice.deadline %></td>
        </tr>

        <tr>
          <td>説明</td>
          <td><%= @notice.explanation %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @notice.title %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @notice.avg_score %>点（<%= @notice.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>

        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>点数</th>
              <th>内容</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
                <td><%= link_to '削除', admin_notice_path(review), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>