config/routes.rb
Rails.application.routes.draw do

  devise_scope :customer do
  post "customers/guest_sign_in", to: "public/sessions#guest_sign_in"
 end

  scope module: :public do
    root to: "homes#top"

    resource :customers, only:[:edit, :update] do
      get "mypage" => "customers#show"
    end

    resources :reservations, only:[:index, :new, :create, :destroy] do
      member do
        get "complete" => "reservations#complete"
      end
    end

    resources :menus, only:[:index]

    resources :notices, only:[:index] do
      member do
        get "show" => "notices#show"
      end
      collection do
        get "search_tag" => "notices#search_tag"
      end
      resources :reviews, only: [:index, :create]
    end
  end

  namespace :admin do
    root to: "homes#top"

    resources :menus, only:[:index, :new, :create, :destroy]

    resources :notices, only:[:index, :show, :new, :create, :update, :destroy] do
      collection do
        get "search_tag" => "notices#search_tag"
      end
    end

    resources :customers, only:[:index]

    resources :reservations, only:[:index]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip:[:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  GUEST_CUSTOMER_EMAIL = "guest@example.com"
    def self.guest
      find_or_create_by!(email: GUEST_CUSTOMER_EMAIL) do |customer|
        customer.password = SecureRandom.urlsafe_base64
        customer.last_name = "太郎"
        customer.first_name = "田中"
        customer.last_name_furigana = "タロウ"
        customer.first_name_furigana = "タナカ"
        customer.telephone_number = "08012345678"
      end
    end

  def guest_customer?
    email == GUEST_CUSTOMER_EMAIL
  end

  has_many :reservations
  has_many :reviews,dependent: :destroy

  with_options presence: do
    validates :last_name
    validates :first_name
    validates :last_name_furigana
    validates :first_name_furigana
    validates :telephone_number
    validates :email
  end

  def full_name = self.last_name + "　" + self.first_name

  def full_name_furigana = self.last_name_furigana + "　" + self.first_name_furigana

end

app/models/menu.rb
class Menu < ApplicationRecord

  validates :menu_title, presence: true
  validates :menu_sub_title, presence: true
  validates :menu_explanation, presence: true
  validates :price, presence: true
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_many :notice_tags,dependent: :destroy
  has_many :tags,through: :notice_tags
  has_many :reviews,dependent: :destroy

  validates :title, presence: true
  validates :deadline, presence: true
  validates :explanation, presence: true

  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
    end
  end

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end
end

app/models/notice_tag.rb
class NoticeTag < ApplicationRecord
  belongs_to :notice
  belongs_to :tag
  validates :notice_id, presence: true
  validates :tag_id, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord


  belongs_to :customer

  validate :date_before_start
  validate :date_current_today
  validate :date_three_month_end

  def date_before_start
    errors.add(:day, "は過去の日付は選択できません") if day < Date.current
  end

  def date_current_today
    errors.add(:day, "は当日は選択できません。予約画面から正しい日付を選択してください。") if day < (Date.current + 1)
  end

  def date_three_month_end
    errors.add(:day, "は3ヶ月以降の日付は選択できません") if (Date.current >> 3) < day
  end

  def self.check_reservation_day(day)
    if day < Date.current
      return "過去の日付は選択できません。正しい日付を選択してください。"
    elsif day < (Date.current + 1)
      return "当日は選択できません。正しい日付を選択してください。"
    elsif (Date.current >> 3) < day
      return "3ヶ月以降の日付は選択できません。正しい日付を選択してください。"
    end
  end

  def self.reservations_after_three_month
    # 今日から3ヶ月先までのデータを取得
    reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
    reservation_data = []
    reservations.each do |reservation|
      reservations_hash = {}
      reservations_hash.merge!(day: reservation.day.strftime("%Y-%m-%d"), time: reservation.time)
      reservation_data.push(reservations_hash)
    end
    reservation_data
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :notice

  validates :score, presence: true
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :notice_tags,dependent: :destroy, foreign_key: 'tag_id'
  # タグは複数の投稿を持つ　それは、notice_tagsを通じて参照できる
  has_many :notices,through: :notice_tags

  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @customers = Customer.page(params[:page]).per(10)
  end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < ApplicationController

  def index
    @menus = Menu.page(params[:page]).per(6)
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to admin_menus_path
    else
      @menus = Menu.page(params[:page]).per(6)
      render 'index'
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy
    redirect_to admin_menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:menu_title, :menu_sub_title, :menu_explanation, :price)
  end
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController

  def index
    @notices = Notice.page(params[:page]).per(10).order(created_at: :desc)
    @tag_list = Tag.all
  end

  def show
    @notice = Notice.find(params[:id])
    @notice_tags = @notice.tags
    @reviews = @notice.reviews
  end

  def new
    @notice = Notice.new
  end

  def create
    @notice = Notice.new(notice_params)
    tag_list=params[:notice][:name].split(',')
    if @notice.save
      @notice.save_tag(tag_list)
      redirect_to admin_notices_path
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_notices_path
  end

  def search_tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @notices = @tag.notices
  end

  private

    def notice_params
      params.require(:notice).permit(:title, :deadline, :explanation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!, if: :admin_url
    before_action :authenticate_customer!, except: [:top], unless: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/admin/notices_helper.rb
module Admin::NoticesHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Haircut</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/976f20cd40.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="top-header">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">QBR</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_root_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "メニュー一覧", admin_menus_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "お知らせ", admin_notices_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "予約管理", admin_reservations_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-default' %>
              </li>

              <% elsif customer_signed_in? %>
              <li class="nav-item d-flex align-items-center mr-3">
                ようこそ、<%= link_to mypage_customers_path do %>
                <span>
                  <%= current_customer.last_name %><%= current_customer.first_name %>
                </span>
                <% end %>
                  さん！
              </li>
              <li class="nav-item">
                <%= link_to "マイページ", mypage_customers_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "メニュー一覧", menus_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "予約リスト", reservations_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-default' %>
              </li>

            <% else %>
              <li class="nav-item">
                <%= link_to "TOP", root_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-default' %>
              </li>
              <li class="nav-item">
                <%= link_to "ゲストログイン(閲覧用)", customers_guest_sign_in_path, method: :post, class: 'btn btn-default' %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <% if flash[:alert] %>
  　　　　<div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </main>

    <footer>
      <%= link_to root_path, class: 'btn btn-default' do %>
        <i class="fa-solid fa-house"></i>
      <% end %>
    </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '翌月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前週'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: '1週間') %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: '1週間') %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: '翌週'), calendar.url_for_next_view %>
    <% reservations = Reservation.reservations_after_three_month %>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>時間</th>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <td></td>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
        <% times.each do |time| %>
          <tr>
            <td><%= time %></td>
            <% week.each do |day| %>
              <td>
                <% if check_reservation(reservations, day, time) %>
                  <%= '×' %>
                <% else %>
                  <%= link_to new_reservation_path(day: day, time: time) do %>
                    <%= '○' %>
                  <% end %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>